import type { ProtocolService } from '../types';

export const protocolPorts: Record<ProtocolService, number> = {
  anthropic: 8081,
  api: 4000,
  autogpt: 8084,
  dns: 53,
  ftp: 21,
  'ide-configs': 11434,
  langserve: 8000,
  'lm-studio': 1234,
  llamacpp: 8082,
  mcp: 11434,
  node: 11434,
  ollama: 11434,
  openai: 8080,
  smb: 445,
  smtp: 25,
  ssh: 22,
  telnet: 23,
  'text-generation-webui': 5000,
  vllm: 8083,
  worker: 4100,
};

export const protocolFamilies = {
  dashboard: ['api', 'worker'] as const,
  honeypot: [
    'openai',
    'autogpt',
    'ide-configs',
    'langserve',
    'lm-studio',
    'llamacpp',
    'mcp',
    'ollama',
    'anthropic',
    'text-generation-webui',
    'vllm',
    'ssh',
    'ftp',
    'smtp',
    'dns',
    'smb',
    'telnet',
  ] as const,
};