import { apiRequest, assert, login, readSmokeConfig, triggerOpenAiProbe, waitFor } from './smoke-helpers.mjs';

const config = readSmokeConfig();

async function main() {
  const token = await login(config);
  const startedAt = Date.now();
  const baseline = await apiRequest('/export/archives', token);
  const baselineIds = new Set(baseline.map((archive) => archive.id));
  const baselineLiveFeed = await apiRequest('/live-feed/events?service=openai', token);
  const baselineCaptureIds = new Set(baselineLiveFeed.map((event) => event.id));

  await triggerOpenAiProbe(config, `archive-smoke-${Date.now()}`);

  const captureEvent = await waitFor(
    'the captured request created by the archive smoke probe',
    async () => {
      const events = await apiRequest('/live-feed/events?service=openai', token);
      return (
        events.find(
          (event) => !baselineCaptureIds.has(event.id) && new Date(event.timestamp).getTime() >= startedAt,
        ) ?? null
      );
    },
    config,
  );

  const manifest = await waitFor(
    'a new archive manifest',
    async () => {
      const archives = await apiRequest('/export/archives', token);
      return (
        archives.find(
          (archive) => !baselineIds.has(archive.id) && new Date(archive.createdAt).getTime() >= startedAt,
        ) ?? null
      );
    },
    config,
  );

  const archive = await apiRequest(`/export/archives/${manifest.id}`, token);
  assert(archive.manifest.id === manifest.id, 'Expected archive retrieval to match the listed manifest');
  assert(
    archive.content.includes(`"id":"${captureEvent.id}"`),
    'Expected archive payload to contain the captured request generated by this smoke probe',
  );

  console.log(JSON.stringify({ archiveId: manifest.id, filename: archive.filename, ok: true }, null, 2));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});