import { Prisma, prisma } from '@llmtrap/db';
import { defaultResponseConfig, responseConfigSchema, type ResponseConfigRecord } from '@llmtrap/shared';
import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { createHash } from 'node:crypto';

import { AuditService } from '../audit/audit.service';
import type { ManualBackfeedInput } from './templates.schemas';

@Injectable()
export class TemplatesService {
  constructor(@Inject(AuditService) private readonly auditService: AuditService) {}

  async approve(currentUserId: string, templateId: string, ipAddress?: string) {
    const existing = await this.requireTemplate(templateId);
    const updated = await prisma.responseTemplate.update({
      data: { approved: true, burned: false },
      where: { id: templateId },
    });

    await this.auditService.record({ action: 'templates.approve', ip: ipAddress, target: templateId, userId: currentUserId });
    return this.serializeTemplate(updated ?? existing);
  }

  async list(reviewQueueOnly = false) {
    const templates = await prisma.responseTemplate.findMany({
      orderBy: { createdAt: 'desc' },
      take: 100,
      where: reviewQueueOnly ? { approved: false, burned: false } : { burned: false },
    });

    return templates.map((template) => this.serializeTemplate(template));
  }

  async manualBackfeed(currentUserId: string, input: ManualBackfeedInput, ipAddress?: string) {
    const normalizedInput = this.normalizeInput(input);
    const node = await prisma.node.findUnique({ where: { id: normalizedInput.nodeId } });
    if (!node) {
      throw new NotFoundException('Node not found');
    }

    const responseConfig = this.readResponseConfig(node.config);
    if (!responseConfig.proxy.baseUrl.trim() || !responseConfig.proxy.model.trim()) {
      throw new BadRequestException('Node proxy is not configured for backfeed generation');
    }

    const promptHash = this.hashPrompt(normalizedInput.prompt);
    const existing = await prisma.responseTemplate.findUnique({ where: { promptHash } });
    if (existing && !existing.burned) {
      return this.serializeTemplate(existing);
    }

    const generatedResponse = await this.generateResponseText(responseConfig, normalizedInput.prompt);
    const templatePayload = {
      approved: false,
      autoGenerated: true,
      burned: false,
      category: normalizedInput.category,
      keywords: this.readKeywords(normalizedInput),
      modelName: responseConfig.proxy.model,
      promptHash,
      promptText: normalizedInput.prompt,
      responseText: generatedResponse,
      subcategory: normalizedInput.subcategory ?? null,
    };
    const created = await this.persistTemplate(promptHash, existing?.id, templatePayload);

    await this.auditService.record({
      action: 'templates.manual-backfeed',
      details: { nodeId: normalizedInput.nodeId, promptHash },
      ip: ipAddress,
      target: created.id,
      userId: currentUserId,
    });

    return this.serializeTemplate(created);
  }

  async reject(currentUserId: string, templateId: string, ipAddress?: string) {
    const existing = await this.requireTemplate(templateId);
    const updated = await prisma.responseTemplate.update({
      data: { approved: false, burned: true },
      where: { id: templateId },
    });

    await this.auditService.record({ action: 'templates.reject', ip: ipAddress, target: templateId, userId: currentUserId });
    return this.serializeTemplate(updated ?? existing);
  }

  private async generateResponseText(responseConfig: ResponseConfigRecord, prompt: string): Promise<string> {
    const baseUrl = responseConfig.proxy.baseUrl.trim().replace(/\/$/, '');
    const endpoint = baseUrl.endsWith('/chat/completions') ? baseUrl : `${baseUrl}/chat/completions`;
    const headers: Record<string, string> = { 'content-type': 'application/json' };
    const apiKey = responseConfig.proxy.apiKey.trim();

    if (apiKey) {
      headers.authorization = apiKey.toLowerCase().startsWith('bearer ') ? apiKey : `Bearer ${apiKey}`;
    }

    const messages: Array<{ content: string; role: 'system' | 'user' }> = [];
    const systemPrompt = responseConfig.proxy.systemPrompt.trim();
    if (systemPrompt) {
      messages.push({ content: systemPrompt, role: 'system' });
    }
    messages.push({ content: prompt, role: 'user' });

    const attempts = Math.max(1, responseConfig.proxy.maxRetries + 1);
    let lastError: unknown;

    for (let attempt = 0; attempt < attempts; attempt += 1) {
      const controller = new AbortController();
      const timeout = globalThis.setTimeout(() => controller.abort(), responseConfig.proxy.timeoutMs);

      try {
        const response = await globalThis.fetch(endpoint, {
          body: JSON.stringify({ messages, model: responseConfig.proxy.model, stream: false }),
          headers,
          method: 'POST',
          signal: controller.signal,
        });

        if (!response.ok) {
          throw new Error(`Proxy request failed with ${response.status}: ${await response.text()}`);
        }

        const payload = (await response.json()) as {
          choices?: Array<{ message?: { content?: string }; text?: string }>;
          content?: Array<{ text?: string }> | string;
        };

        const content = payload.choices?.[0]?.message?.content ?? payload.choices?.[0]?.text ?? this.normalizeContent(payload.content);
        if (!content?.trim()) {
          throw new Error('Proxy returned an empty response');
        }

        return content.trim();
      } catch (error) {
        lastError = error;
      } finally {
        clearTimeout(timeout);
      }
    }

    throw lastError instanceof Error ? lastError : new Error('Proxy backfeed request failed');
  }

  private normalizeInput(input: ManualBackfeedInput): ManualBackfeedInput {
    const nodeId = input.nodeId.trim();
    const prompt = input.prompt.trim();
    const category = input.category.trim();
    const subcategory = input.subcategory?.trim();

    if (!nodeId) {
      throw new BadRequestException('Node id is required');
    }

    if (!prompt) {
      throw new BadRequestException('Prompt cannot be empty');
    }

    if (!category) {
      throw new BadRequestException('Category cannot be empty');
    }

    return {
      category,
      keywords: input.keywords?.map((keyword) => keyword.trim()).filter((keyword) => keyword.length > 0),
      nodeId,
      prompt,
      subcategory: subcategory ? subcategory : undefined,
    };
  }

  private async persistTemplate(
    promptHash: string,
    existingTemplateId: string | undefined,
    templatePayload: {
      approved: boolean;
      autoGenerated: boolean;
      burned: boolean;
      category: string;
      keywords: string[];
      modelName: string;
      promptHash: string;
      promptText: string;
      responseText: string;
      subcategory: string | null;
    },
  ) {
    try {
      return existingTemplateId
        ? await prisma.responseTemplate.update({
            data: templatePayload,
            where: { id: existingTemplateId },
          })
        : await prisma.responseTemplate.create({
            data: templatePayload,
          });
    } catch (error) {
      if (!existingTemplateId && this.isUniquePromptHashError(error)) {
        const concurrentTemplate = await prisma.responseTemplate.findUnique({ where: { promptHash } });
        if (concurrentTemplate) {
          return concurrentTemplate;
        }
      }

      throw error;
    }
  }

  private isUniquePromptHashError(error: unknown): boolean {
    return Boolean(
      error &&
        typeof error === 'object' &&
        'code' in error &&
        (error as { code?: string }).code === 'P2002',
    );
  }

  private hashPrompt(prompt: string): string {
    return createHash('sha256').update(prompt.trim().toLowerCase()).digest('hex');
  }

  private normalizeContent(content: Array<{ text?: string }> | string | undefined): string {
    if (typeof content === 'string') {
      return content;
    }

    return (content ?? []).map((entry) => entry.text?.trim() ?? '').filter((entry) => entry.length > 0).join(' ');
  }

  private readKeywords(input: ManualBackfeedInput): string[] {
    if (input.keywords?.length) {
      return [...new Set(input.keywords.map((keyword) => keyword.trim()).filter((keyword) => keyword.length > 0))].slice(0, 12);
    }

    return [...new Set(input.prompt.toLowerCase().split(/[^a-z0-9]+/).filter((token) => token.length > 2))].slice(0, 8);
  }

  private readResponseConfig(config: Prisma.JsonValue | null | undefined): ResponseConfigRecord {
    if (!config || typeof config !== 'object' || !('responseConfig' in config)) {
      return defaultResponseConfig;
    }

    const parsed = responseConfigSchema.safeParse((config as { responseConfig?: unknown }).responseConfig ?? {});
    return parsed.success ? parsed.data : defaultResponseConfig;
  }

  private async requireTemplate(templateId: string) {
    const template = await prisma.responseTemplate.findUnique({ where: { id: templateId } });
    if (!template) {
      throw new NotFoundException('Template not found');
    }

    return template;
  }

  private serializeTemplate(template: Prisma.ResponseTemplateGetPayload<Record<string, never>>) {
    return {
      approved: template.approved,
      autoGenerated: template.autoGenerated,
      burned: template.burned,
      category: template.category,
      createdAt: template.createdAt.toISOString(),
      id: template.id,
      keywords: template.keywords,
      modelName: template.modelName,
      promptHash: template.promptHash,
      promptText: template.promptText,
      responseText: template.responseText,
      subcategory: template.subcategory,
      updatedAt: template.updatedAt.toISOString(),
      usageCount: template.usageCount,
    };
  }
}