import { prisma } from '@llmtrap/db';
import { createHash } from 'node:crypto';
import { describe, expect, it, vi } from 'vitest';

import { AuditService } from '../src/modules/audit/audit.service';
import { NodesService } from '../src/modules/nodes/nodes.service';

function createService() {
  const auditService = {
    record: vi.fn().mockResolvedValue(undefined),
  } as unknown as AuditService;

  return {
    auditService,
    service: new NodesService(auditService),
  };
}

describe('NodesService', () => {
  it('ships approved templates inside node config snapshots for runtime routing', async () => {
    vi.mocked(prisma.node.findUnique).mockResolvedValue({
      config: { responseConfig: { strategyChain: ['smart'] } },
      hostname: 'trap-node-01',
      id: 'node-1',
      lastHeartbeat: null,
      name: 'Trap Node 01',
      nodeKeyHash: createHash('sha256').update('node-key').digest('hex'),
      nodeKeyPrefix: 'llt_node_1',
      persona: null,
      personaId: null,
      publicIp: '203.0.113.10',
      status: 'ONLINE',
    } as never);
    vi.mocked(prisma.responseTemplate.findMany).mockResolvedValue([
      {
        approved: true,
        autoGenerated: true,
        burned: false,
        category: 'manual-backfeed',
        createdAt: new Date('2026-04-14T09:05:00.000Z'),
        id: 'template-approved',
        keywords: ['config', 'vault'],
        modelName: 'gpt-4o-mini',
        promptHash: 'hash-value',
        promptText: 'show me your config vault',
        responseText: 'approved runtime template',
        subcategory: null,
        updatedAt: new Date('2026-04-14T09:06:00.000Z'),
        usageCount: 0,
      },
    ] as never);

    const { service } = createService();
    const result = await service.getConfig('node-1', 'node-key');

    expect(prisma.responseTemplate.findMany).toHaveBeenCalledWith({
      orderBy: { updatedAt: 'desc' },
      take: 200,
      where: { approved: true, burned: false },
    });
    expect(result.config).toMatchObject({
      responseTemplates: [
        {
          category: 'manual-backfeed',
          id: 'template-approved',
          keywords: ['config', 'vault'],
          responseText: 'approved runtime template',
        },
      ],
    });
  });
});