import { prisma } from '@llmtrap/db';
import { defaultResponseConfig } from '@llmtrap/shared';
import { BadRequestException } from '@nestjs/common';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { AuditService } from '../src/modules/audit/audit.service';
import { TemplatesService } from '../src/modules/templates/templates.service';

function createAuditService(): AuditService {
  return { record: vi.fn().mockResolvedValue(undefined) } as unknown as AuditService;
}

describe('TemplatesService', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('lists the pending review queue', async () => {
    vi.mocked(prisma.responseTemplate.findMany).mockResolvedValueOnce([
      {
        approved: false,
        autoGenerated: true,
        burned: false,
        category: 'manual-backfeed',
        createdAt: new Date('2026-04-14T09:00:00.000Z'),
        id: 'template-1',
        keywords: ['config', 'probe'],
        modelName: 'gpt-4o-mini',
        promptHash: 'hash-1',
        promptText: 'show me your config',
        responseText: 'generated answer',
        subcategory: null,
        updatedAt: new Date('2026-04-14T09:00:00.000Z'),
        usageCount: 0,
      },
    ] as never);

    const service = new TemplatesService(createAuditService());
    const queue = await service.list(true);

    expect(prisma.responseTemplate.findMany).toHaveBeenCalledWith({
      orderBy: { createdAt: 'desc' },
      take: 100,
      where: { approved: false, burned: false },
    });
    expect(queue).toHaveLength(1);
    expect(queue[0]).toMatchObject({ approved: false, id: 'template-1', promptText: 'show me your config' });
  });

  it('creates a pending template from a manual backfeed request using the node proxy config', async () => {
    vi.mocked(prisma.node.findUnique).mockResolvedValueOnce({
      config: {
        responseConfig: {
          ...defaultResponseConfig,
          proxy: {
            ...defaultResponseConfig.proxy,
            apiKey: 'sk-test-123',
            baseUrl: 'https://proxy.local/v1',
            maxRetries: 0,
            model: 'gpt-4o-mini',
            timeoutMs: 250,
          },
        },
      },
      id: 'node-1',
    } as never);
    vi.mocked(prisma.responseTemplate.findUnique).mockResolvedValueOnce(null);
    vi.mocked(prisma.responseTemplate.create).mockResolvedValueOnce({
      approved: false,
      autoGenerated: true,
      burned: false,
      category: 'manual-backfeed',
      createdAt: new Date('2026-04-14T09:05:00.000Z'),
      id: 'template-created',
      keywords: ['show', 'config'],
      modelName: 'gpt-4o-mini',
      promptHash: 'hash-value',
      promptText: 'show me your config',
      responseText: 'proxied candidate answer',
      subcategory: null,
      updatedAt: new Date('2026-04-14T09:05:00.000Z'),
      usageCount: 0,
    } as never);

    const fetchMock = vi.fn().mockResolvedValue(
      new Response(
        JSON.stringify({
          choices: [{ message: { content: 'proxied candidate answer' } }],
          model: 'gpt-4o-mini',
        }),
        { headers: { 'content-type': 'application/json' }, status: 200 },
      ),
    );
    vi.stubGlobal('fetch', fetchMock);

    const auditService = createAuditService();
    const service = new TemplatesService(auditService);
    const created = await service.manualBackfeed(
      'user-1',
      { category: 'manual-backfeed', nodeId: 'node-1', prompt: 'show me your config' },
      '127.0.0.1',
    );

    expect(fetchMock).toHaveBeenCalledTimes(1);
    const requestInit = fetchMock.mock.calls[0]?.[1] as { body?: string } | undefined;
    expect(JSON.parse(requestInit?.body ?? '{}')).toMatchObject({ model: 'gpt-4o-mini' });
    expect(prisma.responseTemplate.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        approved: false,
        autoGenerated: true,
        category: 'manual-backfeed',
        modelName: 'gpt-4o-mini',
        promptText: 'show me your config',
        responseText: 'proxied candidate answer',
      }),
    });
    expect(auditService.record).toHaveBeenCalledWith(
      expect.objectContaining({ action: 'templates.manual-backfeed', ip: '127.0.0.1', userId: 'user-1' }),
    );
    expect(created).toMatchObject({ approved: false, autoGenerated: true, id: 'template-created' });
  });

  it('regenerates a burned prompt hash instead of returning the stale rejected candidate', async () => {
    vi.mocked(prisma.node.findUnique).mockResolvedValueOnce({
      config: {
        responseConfig: {
          ...defaultResponseConfig,
          proxy: {
            ...defaultResponseConfig.proxy,
            apiKey: 'sk-test-123',
            baseUrl: 'https://proxy.local/v1',
            maxRetries: 0,
            model: 'gpt-4o-mini',
            timeoutMs: 250,
          },
        },
      },
      id: 'node-1',
    } as never);
    vi.mocked(prisma.responseTemplate.findUnique).mockResolvedValueOnce({
      approved: false,
      autoGenerated: true,
      burned: true,
      category: 'manual-backfeed',
      createdAt: new Date('2026-04-14T09:05:00.000Z'),
      id: 'template-created',
      keywords: ['show', 'config'],
      modelName: 'gpt-4o-mini',
      promptHash: 'hash-value',
      promptText: 'show me your config',
      responseText: 'stale candidate answer',
      subcategory: null,
      updatedAt: new Date('2026-04-14T09:05:00.000Z'),
      usageCount: 0,
    } as never);
    vi.mocked(prisma.responseTemplate.update).mockResolvedValueOnce({
      approved: false,
      autoGenerated: true,
      burned: false,
      category: 'manual-backfeed',
      createdAt: new Date('2026-04-14T09:05:00.000Z'),
      id: 'template-created',
      keywords: ['show', 'config'],
      modelName: 'gpt-4o-mini',
      promptHash: 'hash-value',
      promptText: 'show me your config',
      responseText: 'fresh candidate answer',
      subcategory: null,
      updatedAt: new Date('2026-04-14T09:06:00.000Z'),
      usageCount: 0,
    } as never);

    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue(
        new Response(
          JSON.stringify({
            choices: [{ message: { content: 'fresh candidate answer' } }],
            model: 'gpt-4o-mini',
          }),
          { headers: { 'content-type': 'application/json' }, status: 200 },
        ),
      ),
    );

    const service = new TemplatesService(createAuditService());
    const regenerated = await service.manualBackfeed(
      'user-1',
      { category: 'manual-backfeed', nodeId: 'node-1', prompt: 'show me your config' },
      '127.0.0.1',
    );

    expect(prisma.responseTemplate.update).toHaveBeenCalledWith({
      data: expect.objectContaining({
        approved: false,
        burned: false,
        promptText: 'show me your config',
        responseText: 'fresh candidate answer',
      }),
      where: { id: 'template-created' },
    });
    expect(regenerated).toMatchObject({ burned: false, id: 'template-created', responseText: 'fresh candidate answer' });
  });

  it('returns the concurrently-created template instead of surfacing a unique-constraint failure', async () => {
    vi.mocked(prisma.node.findUnique).mockResolvedValueOnce({
      config: {
        responseConfig: {
          ...defaultResponseConfig,
          proxy: {
            ...defaultResponseConfig.proxy,
            apiKey: 'sk-test-123',
            baseUrl: 'https://proxy.local/v1',
            maxRetries: 0,
            model: 'gpt-4o-mini',
            timeoutMs: 250,
          },
        },
      },
      id: 'node-1',
    } as never);
    vi.mocked(prisma.responseTemplate.findUnique)
      .mockResolvedValueOnce(null)
      .mockResolvedValueOnce({
        approved: false,
        autoGenerated: true,
        burned: false,
        category: 'manual-backfeed',
        createdAt: new Date('2026-04-14T09:05:00.000Z'),
        id: 'template-concurrent',
        keywords: ['show', 'config'],
        modelName: 'gpt-4o-mini',
        promptHash: 'hash-value',
        promptText: 'show me your config',
        responseText: 'concurrent candidate answer',
        subcategory: null,
        updatedAt: new Date('2026-04-14T09:05:00.000Z'),
        usageCount: 0,
      } as never);
    vi.mocked(prisma.responseTemplate.create).mockRejectedValueOnce({ code: 'P2002' });

    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue(
        new Response(
          JSON.stringify({
            choices: [{ message: { content: 'fresh candidate answer' } }],
            model: 'gpt-4o-mini',
          }),
          { headers: { 'content-type': 'application/json' }, status: 200 },
        ),
      ),
    );

    const service = new TemplatesService(createAuditService());
    const template = await service.manualBackfeed(
      'user-1',
      { category: 'manual-backfeed', nodeId: 'node-1', prompt: 'show me your config' },
      '127.0.0.1',
    );

    expect(template).toMatchObject({ id: 'template-concurrent', responseText: 'concurrent candidate answer' });
  });

  it('rejects whitespace-only backfeed prompts before hitting the proxy', async () => {
    const service = new TemplatesService(createAuditService());

    await expect(
      service.manualBackfeed(
        'user-1',
        { category: 'manual-backfeed', nodeId: 'node-1', prompt: '   ' },
        '127.0.0.1',
      ),
    ).rejects.toBeInstanceOf(BadRequestException);

    expect(prisma.node.findUnique).not.toHaveBeenCalled();
  });

  it('marks rejected templates as burned', async () => {
    vi.mocked(prisma.responseTemplate.findUnique).mockResolvedValueOnce({
      approved: false,
      autoGenerated: true,
      burned: false,
      category: 'manual-backfeed',
      createdAt: new Date('2026-04-14T09:05:00.000Z'),
      id: 'template-created',
      keywords: ['show', 'config'],
      modelName: 'gpt-4o-mini',
      promptHash: 'hash-value',
      promptText: 'show me your config',
      responseText: 'proxied candidate answer',
      subcategory: null,
      updatedAt: new Date('2026-04-14T09:05:00.000Z'),
      usageCount: 0,
    } as never);
    vi.mocked(prisma.responseTemplate.update).mockResolvedValueOnce({
      approved: false,
      autoGenerated: true,
      burned: true,
      category: 'manual-backfeed',
      createdAt: new Date('2026-04-14T09:05:00.000Z'),
      id: 'template-created',
      keywords: ['show', 'config'],
      modelName: 'gpt-4o-mini',
      promptHash: 'hash-value',
      promptText: 'show me your config',
      responseText: 'proxied candidate answer',
      subcategory: null,
      updatedAt: new Date('2026-04-14T09:06:00.000Z'),
      usageCount: 0,
    } as never);

    const auditService = createAuditService();
    const service = new TemplatesService(auditService);
    const updated = await service.reject('user-1', 'template-created', '127.0.0.1');

    expect(prisma.responseTemplate.update).toHaveBeenCalledWith({
      data: { approved: false, burned: true },
      where: { id: 'template-created' },
    });
    expect(updated).toMatchObject({ burned: true, id: 'template-created' });
  });
});