-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'ANALYST', 'VIEWER');

-- CreateEnum
CREATE TYPE "NodeStatus" AS ENUM ('PENDING', 'ONLINE', 'OFFLINE', 'DISABLED');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "UserRole" NOT NULL DEFAULT 'VIEWER',
    "totpSecret" TEXT,
    "totpEnabled" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserSession" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "refreshTokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Persona" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "preset" TEXT,
    "identity" JSONB NOT NULL,
    "hardware" JSONB NOT NULL,
    "models" JSONB NOT NULL,
    "services" JSONB NOT NULL,
    "configFiles" JSONB NOT NULL,
    "timing" JSONB NOT NULL,
    "credentials" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Persona_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Node" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "hostname" TEXT,
    "publicIp" TEXT,
    "nodeKeyHash" TEXT NOT NULL,
    "nodeKeyPrefix" TEXT NOT NULL,
    "status" "NodeStatus" NOT NULL DEFAULT 'PENDING',
    "lastHeartbeat" TIMESTAMP(3),
    "personaId" TEXT,
    "config" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Node_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Actor" (
    "id" TEXT NOT NULL,
    "label" TEXT,
    "headerFingerprint" TEXT,
    "tlsFingerprints" TEXT[],
    "userAgents" TEXT[],
    "firstSeen" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastSeen" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sessionCount" INTEGER NOT NULL DEFAULT 0,
    "mergedFrom" TEXT[],

    CONSTRAINT "Actor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "HoneypotSession" (
    "id" TEXT NOT NULL,
    "nodeId" TEXT NOT NULL,
    "sourceIp" TEXT NOT NULL,
    "userAgent" TEXT,
    "service" TEXT NOT NULL,
    "classification" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" TIMESTAMP(3),
    "requestCount" INTEGER NOT NULL DEFAULT 0,
    "actorId" TEXT,

    CONSTRAINT "HoneypotSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CapturedRequest" (
    "id" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "nodeId" TEXT NOT NULL,
    "sessionId" TEXT,
    "sourceIp" TEXT NOT NULL,
    "sourcePort" INTEGER,
    "protocol" TEXT NOT NULL,
    "service" TEXT NOT NULL,
    "method" TEXT NOT NULL,
    "path" TEXT,
    "headers" JSONB,
    "headerHash" TEXT,
    "userAgent" TEXT,
    "requestBody" JSONB,
    "responseCode" INTEGER,
    "responseBody" JSONB,
    "responseStrategy" TEXT,
    "tlsFingerprint" TEXT,
    "classification" TEXT,
    "geo" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CapturedRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ResponseTemplate" (
    "id" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "subcategory" TEXT,
    "promptHash" TEXT,
    "promptText" TEXT NOT NULL,
    "responseText" TEXT NOT NULL,
    "modelName" TEXT,
    "keywords" TEXT[],
    "burned" BOOLEAN NOT NULL DEFAULT false,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "approved" BOOLEAN NOT NULL DEFAULT true,
    "usageCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ResponseTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AlertRule" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "conditions" JSONB NOT NULL,
    "severity" TEXT NOT NULL,
    "channels" TEXT[],
    "cooldownMin" INTEGER NOT NULL DEFAULT 5,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AlertRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AlertLog" (
    "id" TEXT NOT NULL,
    "ruleId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "channel" TEXT NOT NULL,
    "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "success" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "AlertLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "IpEnrichment" (
    "ip" TEXT NOT NULL,
    "country" TEXT,
    "city" TEXT,
    "region" TEXT,
    "asn" TEXT,
    "org" TEXT,
    "isp" TEXT,
    "ispType" TEXT,
    "reverseDns" TEXT,
    "isKnownBad" BOOLEAN NOT NULL DEFAULT false,
    "abuseScore" DOUBLE PRECISION,
    "isTor" BOOLEAN NOT NULL DEFAULT false,
    "isVpn" BOOLEAN NOT NULL DEFAULT false,
    "cloudProvider" TEXT,
    "enrichedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "IpEnrichment_pkey" PRIMARY KEY ("ip")
);

-- CreateTable
CREATE TABLE "BudgetEntry" (
    "id" TEXT NOT NULL,
    "nodeId" TEXT,
    "month" TEXT NOT NULL,
    "tokensSent" INTEGER NOT NULL DEFAULT 0,
    "tokensRecv" INTEGER NOT NULL DEFAULT 0,
    "estimatedCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "limitCost" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BudgetEntry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "target" TEXT,
    "details" JSONB,
    "ip" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "UserSession_refreshTokenHash_key" ON "UserSession"("refreshTokenHash");

-- CreateIndex
CREATE INDEX "UserSession_userId_expiresAt_idx" ON "UserSession"("userId", "expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "Persona_name_key" ON "Persona"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Node_nodeKeyHash_key" ON "Node"("nodeKeyHash");

-- CreateIndex
CREATE UNIQUE INDEX "Node_nodeKeyPrefix_key" ON "Node"("nodeKeyPrefix");

-- CreateIndex
CREATE INDEX "Node_status_lastHeartbeat_idx" ON "Node"("status", "lastHeartbeat");

-- CreateIndex
CREATE INDEX "HoneypotSession_actorId_idx" ON "HoneypotSession"("actorId");

-- CreateIndex
CREATE INDEX "HoneypotSession_nodeId_startedAt_idx" ON "HoneypotSession"("nodeId", "startedAt");

-- CreateIndex
CREATE INDEX "HoneypotSession_sourceIp_idx" ON "HoneypotSession"("sourceIp");

-- CreateIndex
CREATE INDEX "CapturedRequest_classification_idx" ON "CapturedRequest"("classification");

-- CreateIndex
CREATE INDEX "CapturedRequest_nodeId_timestamp_idx" ON "CapturedRequest"("nodeId", "timestamp");

-- CreateIndex
CREATE INDEX "CapturedRequest_nodeId_service_timestamp_idx" ON "CapturedRequest"("nodeId", "service", "timestamp");

-- CreateIndex
CREATE INDEX "CapturedRequest_service_idx" ON "CapturedRequest"("service");

-- CreateIndex
CREATE INDEX "CapturedRequest_sessionId_idx" ON "CapturedRequest"("sessionId");

-- CreateIndex
CREATE INDEX "CapturedRequest_sourceIp_idx" ON "CapturedRequest"("sourceIp");

-- CreateIndex
CREATE UNIQUE INDEX "ResponseTemplate_promptHash_key" ON "ResponseTemplate"("promptHash");

-- CreateIndex
CREATE INDEX "ResponseTemplate_burned_approved_idx" ON "ResponseTemplate"("burned", "approved");

-- CreateIndex
CREATE INDEX "ResponseTemplate_category_idx" ON "ResponseTemplate"("category");

-- CreateIndex
CREATE UNIQUE INDEX "BudgetEntry_nodeId_month_key" ON "BudgetEntry"("nodeId", "month");

-- CreateIndex
CREATE INDEX "AuditLog_action_idx" ON "AuditLog"("action");

-- CreateIndex
CREATE INDEX "AuditLog_userId_createdAt_idx" ON "AuditLog"("userId", "createdAt");

-- AddForeignKey
ALTER TABLE "UserSession" ADD CONSTRAINT "UserSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Node" ADD CONSTRAINT "Node_personaId_fkey" FOREIGN KEY ("personaId") REFERENCES "Persona"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HoneypotSession" ADD CONSTRAINT "HoneypotSession_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "Actor"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HoneypotSession" ADD CONSTRAINT "HoneypotSession_nodeId_fkey" FOREIGN KEY ("nodeId") REFERENCES "Node"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapturedRequest" ADD CONSTRAINT "CapturedRequest_nodeId_fkey" FOREIGN KEY ("nodeId") REFERENCES "Node"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CapturedRequest" ADD CONSTRAINT "CapturedRequest_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "HoneypotSession"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AlertLog" ADD CONSTRAINT "AlertLog_ruleId_fkey" FOREIGN KEY ("ruleId") REFERENCES "AlertRule"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BudgetEntry" ADD CONSTRAINT "BudgetEntry_nodeId_fkey" FOREIGN KEY ("nodeId") REFERENCES "Node"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;