import type { DocsPage } from './docs-page-types';

export const docsHowItWorksPage: DocsPage = {
  eyebrow: 'How it works',
  id: 'how-it-works',
  quickFacts: [
    { label: 'Stacks', value: 'Dashboard + Node' },
    { label: 'AI surfaces', value: '9 LLM endpoints' },
    { label: 'Traditional', value: '7 classic listeners' },
    { label: 'Total protocols', value: '31 emulated services' },
  ],
  relatedPageIds: ['deploy-dashboard', 'configure-node', 'using-dashboard'],
  sections: [
    {
      id: 'high-level-architecture',
      title: 'High-level architecture',
      intro:
        'LLMTrap is a **distributed honeypot platform** split into two independent Docker Compose stacks that communicate over a shared control-plane network.',
      diagram: [
        '┌─────────────────────────────────────────────────────────────────┐',
        '│                     DASHBOARD  STACK                           │',
        '│                                                                │',
        '│  ┌──────────┐  ┌──────────┐  ┌──────────┐  ┌───────────────┐  │',
        '│  │  React /  │  │  NestJS  │  │  BullMQ  │  │  PostgreSQL   │  │',
        '│  │  Vite UI  │──│  API     │──│  Worker  │──│  + Redis      │  │',
        '│  │ :3000     │  │ :4000    │  │          │  │  + MinIO (S3) │  │',
        '│  └──────────┘  └────┬─────┘  └──────────┘  └───────────────┘  │',
        '└─────────────────────┼──────────────────────────────────────────┘',
        '                      │  REST API  (mTLS / x-node-key)',
        '                      │',
        '┌─────────────────────┼──────────────────────────────────────────┐',
        '│  NODE STACK         │                                          │',
        '│                     ▼                                          │',
        '│  ┌──────────────────────────────────────────────────────────┐  │',
        '│  │  NestJS  Honeypot  Container                             │  │',
        '│  │                                                          │  │',
        '│  │  ┌─────────┐ ┌─────────┐ ┌─────────┐ ┌──────────────┐  │  │',
        '│  │  │ AI LLM  │ │  RAG    │ │ Homelab │ │  Traditional │  │  │',
        '│  │  │ 9 svc   │ │ 5 svc   │ │ 10 svc  │ │  7 listeners │  │  │',
        '│  │  └─────────┘ └─────────┘ └─────────┘ └──────────────┘  │  │',
        '│  └─────────────────────────────┬────────────────────────────┘  │',
        '│                                │                               │',
        '│              ┌─────────────────▼──────────────────┐            │',
        '│              │  Local Redis  (capture buffer)     │            │',
        '│              └────────────────────────────────────┘            │',
        '└────────────────────────────────────────────────────────────────┘',
      ].join('\n'),
      body: [
        'The **Dashboard stack** is your central control plane. It runs the NestJS API, a React/Vite frontend, a BullMQ worker for background jobs, **PostgreSQL** for persistence, **Redis** for caching and pub/sub, and **MinIO** for S3-compatible cold storage.',
        'The **Node stack** is the honeypot itself. Each node runs a single NestJS container with **31 protocol emulators** listening on separate ports, plus a local Redis for autonomous buffering. When an attacker probes any port, the node captures the full request, classifies it, generates a persona-consistent response, and queues the record.',
        'Nodes authenticate to the dashboard using a shared secret (`x-node-key`) issued during enrollment. The dashboard must **approve** the node before it can pull configuration or upload captures.',
      ],
    },
    {
      id: 'protocol-emulation',
      title: 'Protocol emulation layer',
      intro:
        'Every node emulates **31 services** across four categories. Each emulator is a dedicated NestJS module with its own controller, port, and response logic.',
      callout: { text: 'All emulators run inside a single container — no extra VMs or sidecars needed. Ports map 1:1 via Docker Compose.', variant: 'tip' },
      bullets: [
        '**AI LLM surfaces (9)** — `Ollama` (11434), `OpenAI` (8080), `Anthropic` (8081), `LM Studio` (1234), `llama.cpp` (8082), `vLLM` (8083), `text-generation-webui` (5000), `LangServe` (8000), `AutoGPT` (8084). Each emulates the real API surface: model listing, chat completions, streaming responses, and health endpoints.',
        '**RAG vector databases (5)** — `Qdrant` (6333), `ChromaDB` (8085), `Neo4j` (7474), `Weaviate` (8086), `Milvus` (19530). These mimic collection/index listing and status endpoints that scanners probe for open vector stores.',
        '**Homelab services (10)** — `Plex`, `Sonarr`, `Radarr`, `Prowlarr`, `Portainer`, `Home Assistant`, `Gitea`, `Grafana`, `Prometheus`, `Uptime Kuma`. These attract lateral movement and config credential scraping.',
        '**Traditional listeners (7)** — `SSH` (10022), `FTP` (10021), `SMTP` (10025), `SMTP Submission` (10587), `DNS` (1053/udp), `SMB` (10445), `Telnet` (10023). Raw TCP/UDP handlers with banners and interactive bait.',
        '**Specialized surfaces** — `MCP` (JSON-RPC tool/resource bait) and IDE config files (`.claude/settings.json`, `.cursor/mcp.json`, `.continue/config.json`) served at well-known paths.',
      ],
    },
    {
      id: 'capture-pipeline',
      title: 'Capture and classification pipeline',
      intro:
        'Every inbound request flows through a **unified capture pipeline** that extracts metadata, classifies the attack, and routes it to the dashboard.',
      diagram: [
        '  ┌──────────────┐     ┌──────────────┐     ┌──────────────┐',
        '  │  1. INTERCEPT │────▶│  2. CLASSIFY  │────▶│  3. RESPOND  │',
        '  │  Extract IP,  │     │  free_rider   │     │  Template or │',
        '  │  headers,     │     │  scanner      │     │  static JSON │',
        '  │  body, TLS    │     │  config_hunter│     │  + persona   │',
        '  │  fingerprint  │     │  attacker     │     │  variables   │',
        '  └──────────────┘     │  mcp_prober   │     └──────────────┘',
        '                       │  validator     │',
        '                       └──────┬───────┘',
        '                              │',
        '                              ▼',
        '                ┌──────────────────────────┐',
        '                │  4. BUFFER  (local Redis) │',
        '                └────────────┬─────────────┘',
        '                             │ every ~15s',
        '                             ▼',
        '                ┌──────────────────────────┐',
        '                │  5. FLUSH  to dashboard   │',
        '                │  POST /capture/ingest     │',
        '                └──────────────────────────┘',
      ].join('\n'),
      body: [
        '**Step 1 — Intercept.** Each protocol controller intercepts the raw request. The capture middleware extracts: source IP, HTTP method, path, headers, body (truncated at 64 KB), user-agent, and TLS `JA3`/`JA4` fingerprint where available.',
        '**Step 2 — Classify.** The request is classified into one of seven categories: `free_rider` (checking model availability), `scanner` (port/endpoint discovery), `config_hunter` (searching for secrets), `attacker` (exploitation attempt), `mcp_prober` (MCP tool enumeration), `validator` (API key validation), or `unknown`.',
        '**Step 3 — Respond.** The response engine selects a strategy: **static** (hardcoded JSON), **template** (keyword-matched with persona variable substitution), or future **real_model** (LLM proxy). Responses are persona-consistent.',
        '**Step 4 — Buffer.** The captured record is pushed to the local Redis list. This ensures **no data loss** if the dashboard is temporarily unreachable.',
        '**Step 5 — Flush.** A scheduler (default every 15 seconds) drains the Redis list and sends a batch POST to `/api/v1/capture/ingest`.',
      ],
    },
    {
      id: 'persona-engine',
      title: 'Persona engine',
      intro:
        'The persona engine ensures every response from a node looks like it came from a **single, consistent AI deployment** — not a honeypot.',
      callout: { text: 'A scanner querying `/api/version` on the Ollama surface sees the **same model name** that appears in a `/v1/chat/completions` response on the OpenAI surface. Consistency is key to deception.', variant: 'info' },
      body: [
        'A persona definition includes: a **hostname** (e.g., `gpu-worker-03`), a **primary model** (e.g., `deepseek-r1:70b`), **GPU hardware** (e.g., `NVIDIA A100 80GB`), **timing parameters** (inference latency range, startup jitter), **credentials** (dummy API keys), and a **service toggle map** for which emulators are active.',
        'Three built-in presets ship with LLMTrap: **homelabber** (hobbyist on consumer hardware), **researcher** (academic with high-end GPUs), and **startup** (small company with production inference). You can create custom personas from the dashboard.',
        'When the response engine generates a reply, template variables like `{{modelName}}`, `{{hostname}}`, and `{{gpuModel}}` are substituted from the active persona snapshot.',
      ],
    },
    {
      id: 'response-engine',
      title: 'Response engine',
      intro:
        'The response engine turns captured requests into **believable replies** using a template library and persona-aware variable substitution.',
      body: [
        '**Template matching.** When a prompt arrives, the engine scores it against the keyword fields of all approved templates. The best-matching template is selected and its `responseText` is filled with persona variables. If no template exceeds the confidence threshold, a generic fallback is returned.',
        '**Streaming support.** For endpoints that accept `stream: true`, the engine splits the response into token-sized chunks and delivers them as **Server-Sent Events** with realistic inter-token delays from the persona\'s timing profile.',
        '**Template approval workflow.** New templates enter a review queue. Only **approved** templates are eligible for live routing — this prevents low-quality or unsafe responses from reaching attackers.',
        '**Starter templates.** LLMTrap ships with `templates/core.json` covering common prompts: code generation, summarization, translation, and system-prompt extraction attempts.',
      ],
    },
    {
      id: 'node-dashboard-sync',
      title: 'Node ↔ Dashboard synchronization',
      intro:
        'Nodes and the dashboard stay in sync through **four background loops**: registration, heartbeat, config refresh, and capture flush.',
      diagram: [
        '  NODE                                             DASHBOARD',
        '  ────                                             ─────────',
        '    │                                                  │',
        '    │──── POST /register (node key) ──────────────▶│',
        '    │◀─── 200 OK  (node approved) ─────────────────│',
        '    │                                                  │',
        '    │──── POST /heartbeat  (every 30s) ───────────▶│',
        '    │◀─── 200 OK  (status updated) ────────────────│',
        '    │                                                  │',
        '    │──── GET  /nodes/:id/config  (every 60s) ────▶│',
        '    │◀─── 200 { strategy, templates, toggles } ────│',
        '    │                                                  │',
        '    │──── POST /capture/ingest  (batch flush) ────▶│',
        '    │◀─── 200 OK ──────────────────────────────────│',
        '    │                                                  │',
      ].join('\n'),
      body: [
        '**Registration.** On startup the node sends a POST with its node key. The dashboard validates the key and marks the node as connected.',
        '**Heartbeat.** Every 30 seconds, the node sends uptime, capture count, and current status. If heartbeats stop, the node transitions to **OFFLINE**.',
        '**Config refresh.** Every 60 seconds, the node pulls its latest configuration — response strategy, approved template IDs, and per-service toggles. Changes take effect **immediately**.',
        '**Capture flush.** Buffered records are sent in batch on each heartbeat. If the dashboard is unreachable, records stay in Redis and retry on the next connection.',
      ],
    },
    {
      id: 'worker-jobs',
      title: 'Background worker jobs',
      intro:
        'The worker process runs **three long-lived BullMQ processors** that handle tasks the API delegates asynchronously.',
      bullets: [
        '**Alert processor** — Evaluates alert rules against new captures. When a rule matches (e.g., classification = `attacker`, service = `ssh`), the processor fires a POST to the configured webhook URL. Delivery results (status code, latency) are stored as alert logs.',
        '**Archive processor** — On a cron interval (default **6 hours**), scans for sessions older than the retention window (default **30 days**), compresses them into gzipped NDJSON bundles, uploads to MinIO/S3, and prunes old database rows.',
        '**Actor correlation** — Groups captured sessions by source IP, user-agent, and TLS fingerprint into **threat actor profiles**. Each actor gets a summary of services targeted, classification breakdown, and timeline.',
      ],
    },
    {
      id: 'security-model',
      title: 'Security model',
      intro:
        'LLMTrap isolates honeypot traffic from the control plane and enforces **authentication at every boundary**.',
      callout: { text: 'Traditional listeners (SSH, FTP, Telnet) present banners and interactive prompts but **never execute commands** on the host. The honeypot container runs as a non-root user with resource limits.', variant: 'warning' },
      bullets: [
        '**Network isolation.** The node compose exposes only honeypot ports externally. The control-plane network is internal — attackers **cannot reach** the dashboard API or PostgreSQL from a honeypot port.',
        '**Node authentication.** Every API call from a node includes the `x-node-key` header. The dashboard rejects requests from unknown or unapproved nodes.',
        '**Operator authentication.** Dashboard login uses **JWT** with short-lived access tokens (15 min) and longer refresh tokens. **TOTP** two-factor authentication is available in Settings.',
        '**Audit trail.** Every login, node approval, config change, and template approval is recorded. The **Threat Intel** page surfaces IOC, MITRE ATT&CK mapping, blocklists, and STIX bundle exports.',
      ],
    },
    {
      id: 'data-flow-summary',
      title: 'End-to-end data flow',
      intro:
        'Here is the complete journey of a single attacker request from first contact to the dashboard.',
      diagram: [
        '  Attacker                Node Container               Dashboard',
        '  ────────                ──────────────               ─────────',
        '      │                        │                           │',
        '   1. │── POST /v1/chat ──────▶│                           │',
        '      │                        │                           │',
        '      │                  2. Intercept + Classify           │',
        '      │                        │                           │',
        '      │                  3. Template match + persona       │',
        '   4. │◀── SSE stream ────────│                           │',
        '      │                        │                           │',
        '      │                  5. Buffer → Redis                 │',
        '      │                        │                           │',
        '      │                  6. Flush │── POST /ingest ──────▶│',
        '      │                        │                     7. Persist → PG',
        '      │                        │                     8. Pub/sub → WS',
        '      │                        │                     9. Alert rules',
        '      │                        │                    10. Actor correlate',
        '      │                        │                           │',
        '      │                        │                    11. Operator sees',
        '      │                        │                        Live Feed',
      ].join('\n'),
      body: [
        '**Steps 1–4:** Attacker sends a request → node intercepts, classifies, and returns a persona-consistent streaming response.',
        '**Steps 5–6:** The captured record is buffered in local Redis and flushed to the dashboard on the next heartbeat cycle.',
        '**Steps 7–8:** The dashboard persists the record in PostgreSQL and fans it out via Redis pub/sub to the **live-feed WebSocket**.',
        '**Steps 9–10:** The worker evaluates **alert rules** and groups the capture with prior requests from the same source IP into **actor profiles**.',
        '**Step 11:** The operator sees the request appear in **Live Feed**, the session in **Sessions**, and the actor in **Actors**.',
      ],
    },
  ],
  summary:
    'Deep dive into how LLMTrap works: the two-stack architecture, protocol emulation, capture pipeline, persona and response engines, node↔dashboard sync, background workers, and the security model.',
  title: 'How it works',
};
